// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kptgnpxyarxnyjivenqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdGducHh5YXJ4bnlqaXZlbnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTIyNDIsImV4cCI6MjA2MTA4ODI0Mn0.ei64IeRdoB82v2RYbiw_IK6FBScSQF-TpBFbjmcSZfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);